shopping_cart/config/routes.rb
Rails.application.routes.draw do
  delete 'logout', to: 'sessions#destroy'
  resources :users, :sessions
  resources :products do
    collection do 
      get "add_to_cart/:id", to: "products#add_to_cart",as: "add_to_cart"
      get :show_cart
      get "delete_from_cart/:id", to: "products#delete_from_cart",as: "delete_from_cart"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get "products/add_to_cart", to:"products#add_to_cart"
  # Defines the root path route ("/")
  root to: 'products#index'
end

shopping_cart/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

shopping_cart/app/models/product.rb
class Product < ApplicationRecord
end

shopping_cart/app/models/user.rb
class User < ApplicationRecord
end

shopping_cart/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

shopping_cart/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  
  def add_to_cart
    if session[:product_id]== nil 
      session[:product_id]=[]
    end
    session[:product_id] <<params[:id] 
    
    redirect_to show_cart_products_path
  end
  def show_cart
    
  end
  def delete_from_cart
    if session[:product_id].include?(params[:id])
      #session[:product_id].(session[:product_id].find(params[:id]))
      session[:product_id].delete_at(session[:product_id].index(params[:id])) 
    end
    redirect_to show_cart_products_path
  end

  # GET /products or /products.json
  def index
    
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        expire_fragment('products')
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        expire_fragment('products')
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

shopping_cart/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in successfully'
  end

  def destroy
    session.delete(:user_id)
    session.delete(:product_id)

    redirect_to new_session_path, notice: 'Logged out successfully'
  end
end

shopping_cart/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Account created successfully'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password_digest)
  end
end

shopping_cart/app/helpers/application_helper.rb
module ApplicationHelper
end

shopping_cart/app/helpers/cart_helper.rb
module CartHelper
end

shopping_cart/app/helpers/products_helper.rb
module ProductsHelper
end

shopping_cart/app/helpers/sessions_helper.rb
module SessionsHelper
end

shopping_cart/app/helpers/users_helper.rb
module UsersHelper
end

shopping_cart/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

shopping_cart/app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div>
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

shopping_cart/app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

</div>

shopping_cart/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

shopping_cart/app/views/products/index.html.erb
<h1>Products</h1>

<% cache('products') do %>
  <% @products.each do |product| %>
    <div class="product">
      <h2><%= product.name %></h2>
      <p><%= number_to_currency(product.price) %></p>
      <p>
        <%= link_to "Show this product", product ,:class => "btn btn-secondary"%>
        <%=link_to "Add #{product.name} to cart", add_to_cart_products_path(product),:class => "btn btn-primary" %>
      </p>
    </div>
  <% end %>
<% end %>

<%= link_to "New product", new_product_path,:class => "btn btn-danger" %>
<br>
<%= form_tag('/logout', method: :delete) do %>
  <%= submit_tag "Log Out" %>
<% end %>

shopping_cart/app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

shopping_cart/app/views/products/show.html.erb
<p><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

shopping_cart/app/views/products/show_cart.html.erb
<h2>Your Cart</h2>

<table class="table">
  <tr>
    <td>NAME</td>
    <td>QUANTITY</td>
    <td>PRICE</td>
    <td>ADD</td>
    <td>REMOVE</td>
  </tr>



<%session[:product_id].uniq.each do |a|%>
   <tr>
   <td><%= Product.find(a).name%></td>
    
   <td>  <%= session[:product_id].count(a)%></td>
  
   <td> <%= (Product.find(a).price)*session[:product_id].count(a)%></td>
   <td> <%=link_to "+1",add_to_cart_products_path(a),:class => "btn btn-success"%></td>
   <td> <%=link_to "-1",delete_from_cart_products_path(a),:class => "btn btn-primary"%></td>
   </tr>
<%end%>
</table>

<%=link_to "back",root_path,:class => "btn btn-danger"%>