sign_up_page_app/config/routes.rb
Rails.application.routes.draw do
  root "userdata#index"

  resources :userdata

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

sign_up_page_app/app/models/user.rb
class User < ApplicationRecord
  before_create :upcase_firstname_lastname
  after_create :send_welcome_email
  before_save :calculate_plan_days
  after_save :print_plan_days
  validates :firstname, :lastname, presence: true

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 
  validates :email, uniqueness: true

  validates :username, exclusion: { in: %w(test bacancy),
  message: "%{value} is reserved." }


  validates :planenddate, comparison: { greater_than: :planstartdate }

  validates :phonenumber, length: { is: 10 }
  validates :zipcode, length: { minimum: 6 }

  validates :password, length: { in: 6..20 }

  private

  def upcase_firstname_lastname
    self.firstname = firstname.upcase
    self.lastname = lastname.upcase
  end

  
  def send_welcome_email
    puts "Welcome User in this form"
  end

  def calculate_plan_days
    self.totaldaysofplan = planenddate.day - planstartdate.day
  end

  def print_plan_days
    puts totaldaysofplan
  end
end

sign_up_page_app/app/controllers/userdata_controller.rb
class UserdataController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @userdata_url
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :username, :password, :phonenumber, :zipcode, :planstartdate, :planenddate)
    end
end

sign_up_page_app/app/helpers/userdata_helper.rb
module UserdataHelper
end

sign_up_page_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SignUpPageApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

sign_up_page_app/app/views/userdata/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>
    <li>
      <a href="/userdata/<%= user.id %>">
        User <%= user.id %>
      </a>
    </li>
  <% end %>
</ul>

<%= link_to "New User", new_userdatum_path %>

sign_up_page_app/app/views/userdata/new.html.erb
<h1>New User</h1>

<%= form_for @user, url: userdata_path do |form| %>
  <div>
    <%= form.label :FirstName %><br>
    <%= form.text_field :firstname %>
    <% @user.errors.full_messages_for(:firstname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :LastName %><br>
    <%= form.text_field :lastname %>
    <% @user.errors.full_messages_for(:lastname).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Email %><br>
    <%= form.text_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Username %><br>
    <%= form.text_field :username %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Password %><br>
    <%= form.text_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Mobile %><br>
    <%= form.text_field :phonenumber %>
    <% @user.errors.full_messages_for(:phonenumber).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Zipcode %><br>
    <%= form.text_field :zipcode %>
    <% @user.errors.full_messages_for(:zipcode).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Plan_Start_Date %><br>
    <%= form.date_field :planstartdate %>
  </div>

  <div>
    <%= form.label :Plan_End_Date %><br>
    <%= form.date_field :planenddate %>
    <% @user.errors.full_messages_for(:planenddate).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :Plan_Days %><br>
    <%= form.number_field :totaldaysofplan %>
    <% @user.errors.full_messages_for(:totaldaysofplan).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

sign_up_page_app/app/views/userdata/show.html.erb
<h1>User <%= @user.id %></h1>

<p>First Name: <%= @user.firstname %></p>
<p>Last Name: <%= @user.lastname %></p>
<p>Email: <%= @user.email %></p>
<p>Username: <%= @user.username %></p>
<p>Password: <%= @user.password %></p>
<p>Mobile: </p><%= @user.phonenumber %></p>
<p>Zipcode: <%= @user.zipcode %></p>
<p>Plan Start Date: <%= @user.planstartdate %></p>
<p>Plan End Date: <%= @user.planenddate %></p>
<p>Plan Days: <%= @user.totaldaysofplan %></p>